import { useState } from 'react';
import { getAssistiveSuggestion } from '../api/client';

export default function AssistiveSuggestionPanel() {
  const [suggestion, setSuggestion] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const run = async () => { setBusy(true); setError(''); try { setSuggestion(await getAssistiveSuggestion({ eventType: 'cable_degradation', severity: 'high', confidence: 0.8, impactUsd: 800000 })); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <div className="bg-panel border border-line rounded-lg p-4"><div className="flex items-center justify-between gap-3"><div><div className="font-mono text-[10px] uppercase tracking-widest text-signal">Assistive triage</div><h2 className="font-display text-lg font-semibold text-ink mt-1">Sugerencia con límites</h2></div><span className="font-mono text-[10px] text-ink-dim">HUMAN IN THE LOOP</span></div><p className="text-xs text-ink-muted mt-2">Propone un playbook y siguientes pasos; no ejecuta acciones ni sustituye al analista.</p><button type="button" onClick={run} disabled={busy} className="bg-signal text-void rounded px-3 py-2 text-xs font-semibold mt-3 disabled:opacity-50">{busy ? 'Analizando...' : 'Generar sugerencia local'}</button>{error && <div role="alert" className="text-xs text-alert mt-3">{error}</div>}{suggestion && <div className="mt-4 border border-line rounded p-3"><div className="flex justify-between gap-2 text-xs"><span className="text-ink">Resultado</span><span className={suggestion.decision === 'suggest' ? 'text-signal' : 'text-alert'}>{suggestion.decision}</span></div><div className="text-sm text-ink mt-2">{suggestion.suggestion.playbookName}</div><div className="text-xs text-ink-muted mt-2">{suggestion.suggestion.rationale}</div>{suggestion.abstainReasons.length > 0 && <div className="text-[10px] text-alert mt-2">Abstenciones: {suggestion.abstainReasons.join(', ')}</div>}<div className="mt-3 space-y-1">{suggestion.suggestion.nextSteps.map((step, index) => <div key={`${step}-${index}`} className="text-[10px] text-ink-dim">{index + 1}. {step}</div>)}</div><div className="font-mono text-[10px] text-ink-dim mt-3">Aprobacion humana: requerida · acciones externas: deshabilitadas</div></div>}</div>;
}
