import { useEffect, useState } from 'react';
import { getHistoricalBenchmarkPlan, getPlaybookReadiness } from '../api/client';

export default function ExecutionCoveragePanel() {
  const [benchmark, setBenchmark] = useState({ status: 'loading', targetEventCount: 10, minimumBacktestEventCount: 3, eligibleEventCount: 0, remainingTargetSlots: 10, gates: {} });
  const [playbooks, setPlaybooks] = useState({ status: 'loading', requiredPlaybooksPerVertical: 5, verticals: [] });
  useEffect(() => { getHistoricalBenchmarkPlan().then(setBenchmark); getPlaybookReadiness().then(setPlaybooks); }, []);
  return <section className="bg-panel border border-line rounded-lg p-4"><div className="font-mono text-[10px] uppercase tracking-widest text-signal">Plan Maestro · cobertura de ejecución</div><h2 className="font-display text-lg font-semibold text-ink mt-1">Gates que no se deben esconder</h2><p className="text-xs text-ink-muted mt-2">Separa la cobertura preparada localmente de la evidencia que sólo puede llegar con datos históricos autorizados y un piloto.</p><div className="grid grid-cols-1 lg:grid-cols-2 gap-3 mt-4"><div className="border border-line rounded p-3"><div className="flex justify-between gap-2"><span className="text-xs text-ink">Benchmark histórico</span><span className="font-mono text-[10px] text-alert">{benchmark.gates?.productionClaim || 'ABSTENCIÓN'}</span></div><div className="grid grid-cols-3 gap-2 mt-3"><Metric label="Elegibles" value={benchmark.eligibleEventCount || 0} /><Metric label="Objetivo" value={benchmark.targetEventCount || 10} /><Metric label="Faltantes" value={benchmark.remainingTargetSlots ?? 10} /></div><div className="text-[10px] text-ink-dim mt-3">Mínimo para revisión inicial: {benchmark.minimumBacktestEventCount || 3}. No se generan eventos sintéticos.</div></div><div className="border border-line rounded p-3"><div className="flex justify-between gap-2"><span className="text-xs text-ink">Playbooks por vertical</span><span className={`font-mono text-[10px] ${playbooks.status === 'ready_for_local_pilot' ? 'text-signal' : 'text-alert'}`}>{playbooks.status}</span></div><div className="space-y-2 mt-3">{(playbooks.verticals || []).map((vertical) => <div key={vertical.id} className="flex justify-between gap-2 text-[10px]"><span className="text-ink-muted">{vertical.label}</span><span className={vertical.pass ? 'text-signal' : 'text-alert'}>{vertical.playbookCount}/{vertical.requiredPlaybooks}</span></div>)}</div><div className="text-[10px] text-ink-dim mt-3">La ejecución externa permanece bloqueada hasta aprobación humana.</div></div></div></section>;
}

function Metric({ label, value }) { return <div className="bg-void border border-line rounded p-2"><div className="font-mono text-[9px] uppercase tracking-widest text-ink-dim">{label}</div><div className="font-display text-sm font-semibold text-ink mt-1">{value}</div></div>; }
