import { useState } from 'react';
import { Calculator } from 'lucide-react';
import { buildPilotValueCase } from '../api/client';

export default function PilotValueCasePanel() {
  const [draft, setDraft] = useState({ annualEvents: 4, lossPerEventUsd: 100000, mitigationRate: 0.5, platformAnnualCostUsd: 50000, implementationCostUsd: 25000, evidenceRefs: '' });
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');
  const run = async (event) => { event.preventDefault(); setError(''); try { setResult(await buildPilotValueCase({ ...draft, evidenceRefs: draft.evidenceRefs.split(',').map((item) => item.trim()).filter(Boolean) })); } catch (failure) { setError(failure.message); } };
  return <section className="bg-panel border border-line rounded-lg overflow-hidden"><div className="p-4 border-b border-line flex items-center gap-3"><Calculator size={16} className="text-signal" /><div><div className="font-mono text-[10px] uppercase tracking-widest text-signal">Pilot value case</div><h2 className="font-display font-semibold text-ink mt-1">Evidence-Based Economic Case</h2></div></div><form onSubmit={run} className="p-4 grid grid-cols-2 md:grid-cols-6 gap-2"><input className="control" type="number" min="0" step="1" value={draft.annualEvents} onChange={(event) => setDraft({ ...draft, annualEvents: event.target.value })} placeholder="Events/year" aria-label="Events per year" /><input className="control" type="number" min="0" step="1000" value={draft.lossPerEventUsd} onChange={(event) => setDraft({ ...draft, lossPerEventUsd: event.target.value })} placeholder="Loss/event" aria-label="Loss per event" /><input className="control" type="number" min="0" max="1" step="0.05" value={draft.mitigationRate} onChange={(event) => setDraft({ ...draft, mitigationRate: event.target.value })} placeholder="Mitigation" aria-label="Mitigation rate" /><input className="control" type="number" min="0" step="1000" value={draft.platformAnnualCostUsd} onChange={(event) => setDraft({ ...draft, platformAnnualCostUsd: event.target.value })} placeholder="Annual cost" aria-label="Annual cost" /><input className="control" type="number" min="0" step="1000" value={draft.implementationCostUsd} onChange={(event) => setDraft({ ...draft, implementationCostUsd: event.target.value })} placeholder="Implementation" aria-label="Implementation cost" /><button className="border border-signal/40 text-signal rounded px-3 py-2 text-xs">Calculate</button><input className="control col-span-2 md:col-span-6" value={draft.evidenceRefs} onChange={(event) => setDraft({ ...draft, evidenceRefs: event.target.value })} placeholder="Evidence references, comma-separated" aria-label="Evidence references" /></form>{error && <div role="alert" className="px-4 pb-3 text-xs text-alert">{error}</div>}{result && <div className="p-4 pt-0"><div className="grid grid-cols-2 md:grid-cols-5 gap-2">{[['Protected value', result.outputs.protectedValueUsd], ['First-year net', result.outputs.firstYearNetValueUsd], ['Annual B/C', result.outputs.annualBenefitCostRatio ?? 'N/D'], ['Payback (months)', result.outputs.paybackMonths ?? 'N/D'], ['Gate', result.status]].map(([label, value]) => <div key={label} className="border border-line rounded p-2"><div className="font-mono text-[9px] uppercase tracking-widest text-ink-dim">{label}</div><div className="text-sm text-ink mt-1">{typeof value === 'number' ? `$${value.toLocaleString('en-US')}` : value}</div></div>)}</div><div className="font-mono text-[10px] text-alert mt-3">willingness-to-pay: not validated</div><p className="text-[10px] text-alert/80 mt-1">{result.disclaimer}</p></div>}</section>;
}



