import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

function formatUsd(value) { if (!Number.isFinite(value)) return '—'; if (value >= 1000000) return `$${(value / 1000000).toFixed(1)}M`; if (value >= 1000) return `$${Math.round(value / 1000)}K`; return `$${Math.round(value)}`; }

export function createScenarioPdf(result, generatedAt = new Date()) {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const marginX = 48;
  doc.setFillColor(10, 17, 32);
  doc.rect(0, 0, 612, 88, 'F');
  doc.setTextColor(45, 212, 191);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('GLOBAL RESILIENCE OS', marginX, 40);
  doc.setTextColor(139, 152, 180);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Scenario report - Submarine cable infrastructure disruption', marginX, 56);
  doc.text(`Generated: ${generatedAt.toLocaleString('es-MX')}`, marginX, 70);

  let y = 110;
  doc.setTextColor(20, 20, 20);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(`Cable: ${result.cable.name}`, marginX, y);
  y += 16;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Route: ${result.cable.route}`, marginX, y);
  y += 14;
  doc.text(`Scenario: ${result.severity === 'total' ? 'Total outage' : 'Partial outage'} - Duration: ${result.durationHours}h`, marginX, y);
  y += 14;
  if (result.chokepoints?.length) { doc.text(`Route chokepoints: ${result.chokepoints.join(', ')}`, marginX, y); y += 14; }
  y += 10;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(251, 146, 60);
  doc.text(`Total estimated loss: ${formatUsd(result.totalUsdLoss)}`, marginX, y);
  doc.setTextColor(20, 20, 20);

  autoTable(doc, {
    startY: y + 24,
    head: [['Vertical', 'Impact category', 'Impact %', 'Estimated loss (USD)']],
    body: (result.affected || []).map((item) => [item.label, item.tier === 'direct' ? 'Direct' : item.tier === 'moderate' ? 'Moderate' : 'Systemic', `${(item.impactPct * 100).toFixed(1)}%`, formatUsd(item.usdLoss)]),
    styles: { font: 'helvetica', fontSize: 9, cellPadding: 5 },
    headStyles: { fillColor: [16, 27, 46], textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    margin: { left: marginX, right: marginX },
  });

  let finalY = (doc.lastAutoTable?.finalY || y + 40) + 20;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('Scenario readout', marginX, finalY);
  finalY += 14;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const narrativeLines = doc.splitTextToSize(result.narrative || 'No narrative available.', 612 - marginX * 2);
  doc.text(narrativeLines, marginX, finalY);
  finalY += narrativeLines.length * 12 + 20;
  doc.setFillColor(250, 240, 225);
  doc.rect(marginX, finalY, 612 - marginX * 2, 40, 'F');
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(120, 80, 30);
  const disclaimer = doc.splitTextToSize('This report was generated by a functional Global Resilience OS demo. Daily flow values are illustrative estimates and must not be used for real investment, trading, or risk hedging decisions.', 612 - marginX * 2 - 16);
  doc.text(disclaimer, marginX + 8, finalY + 12);
  return doc;
}



